#!/bin/bash
# Author: John Ballen
# Date Created:04-22-2021
# Description: This script will check files 
# Date Modified: 04-22-2021

FILES="/etc/passwd
/etc/group
/etc/shadow
/etc/nsswitch.conf
/etc/sshd_ssh_config
/etc/fake"

echo
for file in $FILES
do
#-e = exists | diferent to exist= "!-e"
	if [ ! -e $file ]
	then
	echo $file do not exists
	echo
	fi
done
