#!/bin/bash
# Author: John Ballen
# Date Created:04-22-2021
# Description: This script will rename files endign with .txt
# Date Modified: 04-22-2021

for filename in *.txt
do
	mv $filename ${filename%.txt}.none
done


