#!/bin/bash
# Author: John Ballen
# Date Created:04-22-2021
# Description: This script will copy files with scp
# Date Modified: 04-22-2021

#This container has a file with the list of servers
a=`cat /home/john/GIT/BashScript/CopyToRemote/list.txt`
#i is equal to ssh credential (johndoe@192.169.0.x)
for i in $a
do
	scp *.log $i:/tmp
done
