#!/bin/bash
# Author: John Ballen
# Date Created:04-26-2021
# Description: This script manage users
# Date Modified: 04-26-2021

#Command lastlog is useful in order to know the  users and when was the last log
#lastlog -b 90 | tail -n+2 //This command show the users activities three last months.
#-v = exclude

a=`lastlog | tail -n+2 | grep 'test' | awk '{print $1}'`

for i in $a
do
#echo $i
	usermod -L $i
done

