#!/bin/bash
# Author: John Ballen
# Date Created:04-16-2021
# Description: This script will ping a remote host and notify 
# Date Modified: 04-19-2021

hosts='192.168.0.1'
# Dev null is a null file, so that there aren't a ping output
ping -c1 $hosts &> /dev/null
#$? = the output status of the command, like ping. 
	if [ $? -eq 0 ]
	then
	echo $hosts OK.
	else
	echo $hosts NOT OK 
	fi

